resource_path: ["../"]
bibliography: bibliography.bib
citestyle: ieee.csl
reference-location: margin
toc: true
filters:
  - include-code-files

project:
  type: website
  output-dir: "../docs"
  render:
    - index.md
    - introduction_to_bayesian_inference.md
    - mcmc_and_stan.md
    - metropolis-hastings.qmd
    - after_mcmc.qmd
    - regression.qmd
    - hierarchical_models.qmd
    - odes.qmd
    - workflow.md

website:
  title: "Bayesian Statistics for Computational Biology"
  navbar:
    tools:
      - icon: github
        url:  https://github.com/biosustain/bayesian_statistics_for_computational_biology
  sidebar:
    style: "docked"
    serach: true
    contents:
      - section: "Admin"
        contents:
        - index.md
      - section: "Course materials"
        contents:
        - introduction_to_bayesian_inference.md
        - mcmc_and_stan.md
        - metropolis-hastings.qmd
        - after_mcmc.qmd
        - regression.qmd
        - hierarchical_models.qmd
        - odes.qmd
        - workflow.md

format:
  html:
    theme: cosmo
    embed-resources: true
    include-in-header: mathjax.html
  ipynb: default
