resource_path: ["../"]
bibliography: bibliography.bib
citestyle: ieee.csl
reference-location: margin
toc: true

project:
  type: website
  output-dir: "../docs"
  render:
    - index.md
    - week1.md

website:
  title: "Bayesian Statistics for Computational Biology"
  navbar:
    tools:
      - icon: github
        url:  https://github.com/biosustain/bayesian_statistics_for_computational_biology
  sidebar:
    style: "docked"
    serach: true
    contents:
      - section: "Admin"
        contents:
        - index.md
      - section: "Course materials"
        contents:
        - week1.md

format:
  html:
    theme: cosmo
    embed-resources: true
    include-in-header: mathjax.html

